name: flutter_simple_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  material_design_icons_flutter: ^4.0.5145

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

  uses-material-design: true
  assets:
    - assets/images/
